<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;


class TambahanUserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('users')->insert([
            [
                'name' => 'Andrea Georgina Rengkung',
                'email' => '2251099@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Andres',
                'email' => '2251067@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Angel Ryanti Simanjuntak',
                'email' => '2251062@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Apriyanto Samosir',
                'email' => '2251003@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Abigail Stephanie Wuisan',
                'email' => '2251022@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Ably Eunike Grace Sianturi',
                'email' => '2251031@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Adinda Gayatri Puspa Adelin Wijoyo',
                'email' => '2251007@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Airell Azalia Izacson Wakkary',
                'email' => '2251050@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Arca Julianus',
                'email' => '2251061@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Beatries Giovany Sahetapy',
                'email' => '2251002@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Damai Zaya Zalukhu',
                'email' => '2251032@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dewi Widia Anjani',
                'email' => '2251005@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Elvita Juliana Br.Parangin-angin',
                'email' => '2251068@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fiyola Taebenu',
                'email' => '2251020@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fransiska Iriani Intan Permata Sari Wijaya',
                'email' => '2251059@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Fansiska Nela',
                'email' => '2251004@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Gabryela Raquenli Sihombing',
                'email' => '2251063@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Inesti Febrianti Gea',
                'email' => '2251043@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Jeany Eleven Sabath Rondonuwu',
                'email' => '2151045@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Maharani Beaty Yosabat Pakpahan',
                'email' => '2251091@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Marcella Valencia Tan',
                'email' => '2251001@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Meitha Eryani Sitanggang',
                'email' => '2251085@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Neng Riska Paulina',
                'email' => '2251025@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Nova Elisabeth Sihombing',
                'email' => '2251045@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Odilio Nathaniel',
                'email' => '2251127@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Rainer Saerang',
                'email' => '2251014@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Raja Hutajulu',
                'email' => '2251055@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Resa Widiyanti',
                'email' => '2251026@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Reynaldo',
                'email' => '2251054@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sally Kunu',
                'email' => '2251119@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sandrina Janet Clara Herwaman',
                'email' => '2251021@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Sri Melati Silaban',
                'email' => '2251114@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Steyvaini Veronika Bella',
                'email' => '2251012@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Susan Rahmawati',
                'email' => '2251034@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Syifa Nur Atiyah',
                'email' => '2251078@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tomi Lorenzo Kana Wadu',
                'email' => '2251038@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Tuarissa Novalinda Amelia',
                'email' => '2251039@unai.edu',
                'password' => Hash::make('emsaec123'),
                'roles' => 'user',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
